name = "expo-push-worker"
main = "./src/index.ts"
compatibility_date = "2022-05-03"
# TODO: check https://github.com/ionic-team/rollup-plugin-node-polyfills/ for polyfills
node_compat = true

[vars]
EXPO_ACCESS_TOKEN = ""
